nginx-proxy:
    image: "nginx:1.13.3"
    container_name: "nginx-proxy-docker"
    restart: always
    ports:
       - "172.10.11.210:80:80"
    environment:
        NGINX_HOST: nginx.proxy.test.org
        NGINX_PORT: 80
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
